### ISSUE TITLE
咨询请教您关于NSCSCC的一些问题

### ISSUE THREAD

**Issue by SeddonShen** [z4yx/linux-kernel#1]
请教一下学长，使用PMON加载您仓库的Linux Kernel，直接加载就会报协处理器的错误，上板ILA之后感觉是在进入entry之后跑飞，回到了PMON的地址段上，不知道您对这个问题有没有什么理解？
`PMON> g console=ttyS0,115200 rdinit=sbin/init
zero at v0 v1 a0 a1 a2 a3
00000000 00000000 00000000 00000000 00000003 a7dffd78 a7dffd88 870af7f0
t0 t1 t2 t3 t4 t5 t6 t7
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
s0 s1 s2 s3 s4 s5 s6 s7
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
t8 t9 k0 k1 gp sp s8 ra
00000000 00000000 00000000 00000000 00000000 a7dffd58 00000000 8707ad18

Exception Cause=coprocessor unusable, SR=0x10000002, PC=0x8707af40
CONTEXT=0x00000000, XCONTEXT=0x00000064
BADVADDR=0xbfc00000, ENTHI=0x00000064
ENTLO0=0x00000000, ENTLO1=0x00000064

zero at v0 v1 a0 a1 a2 a3
00000000 24000000 34000000 870c0000 870ca050 0000001f 00000000 8700fd90
t0 t1 t2 t3 t4 t5 t6 t7
8700fd90 10000000 00000000 00000001 8032bda1 00000000 00000000 00000010
s0 s1 s2 s3 s4 s5 s6 s7
00000000 00000020 870c7060 00000020 8700fc00 870ca050 870a77ec 870c0000
t8 t9 k0 k1 gp sp s8 ra
00000000 00000000 00000000 00000000 870bc0d0 8700fb38 00000000 87053d74

8707af40 4448f800 cfc1 t0,$31
PMON> `
在此提前谢过了！

**Comment by z4yx** [comment]
从日志来看出错指令是`cfc1`，一条浮点数相关的指令。如果你的处理器不支持浮点，那么内核就不应该执行相关指令。建议反汇编跟踪下调用关系，看看是怎么执行到这个位置的。

**Comment by SeddonShen** [comment]
好的好的，谢谢学长
